### ISSUE TITLE
tf与keras兼容问题报错

### ISSUE THREAD

**Issue by cyning911** [bubbliiiing/yolox-keras#7]
!python predict.py
报错如下：
model_data/yolox_s.h5 model, and classes loaded.
Traceback (most recent call last):
  File "predict.py", line 14, in <module>
    yolo = YOLO()
  File "/content/yolox-keras/yolo.py", line 82, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/content/yolox-keras/yolo.py", line 106, in generate
    letterbox_image = self.letterbox_image
  File "/content/yolox-keras/utils/utils_bbox.py", line 73, in DecodeBox
    grid_x, grid_y = tf.meshgrid(K.arange(hw[i][1]), K.arange(hw[i][0]))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/keras/layers/core/tf_op_layer.py", line 107, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 3510, in arange
    if stop is None and start < 0:
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: Exception encountered when calling layer "tf.keras.backend.arange" (type TFOpLambda).

using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

Call arguments received:
  • start=tf.Tensor(shape=(), dtype=int32)
  • stop=None
  • step=1
  • dtype=int32

修改：utils.utils_bbox.DecodeBox如下：
@tf.function
def DecodeBox()

接着报错：
model_data/yolox_s.h5 model, and classes loaded.
Traceback (most recent call last):
  File "predict.py", line 14, in <module>
    yolo = YOLO()
  File "/content/yolox-keras/yolo.py", line 82, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "/content/yolox-keras/yolo.py", line 106, in generate
    letterbox_image = self.letterbox_image
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/keras_tensor.py", line 256, in __array__
    f'You are passing {self}, an intermediate Keras symbolic input/output, '
TypeError: You are passing KerasTensor(type_spec=TensorSpec(shape=(None, None, None, 85), dtype=tf.float32, name=None), name='concatenate_13/concat:0', description="created by layer 'concatenate_13'"), an intermediate Keras symbolic input/output, to a TF API that does not allow registering custom dispatchers, such as `tf.cond`, `tf.function`, gradient tapes, or `tf.map_fn`. Keras Functional model construction only supports TF API calls that *do* support dispatching, such as `tf.math.add` or `tf.reshape`. Other APIs cannot be called directly on symbolic Kerasinputs/outputs. You can work around this limitation by putting the operation in a custom Keras layer `call` and calling that layer on this symbolic input/output.

**Comment by cyning911** [comment]
B导，麻烦指定一下

**Comment by bubbliiiing** [comment]
0 0 这啥版本啊

**Comment by wangbaoyi** [comment]
希望up能更新tf2.4.0版本或者说最新版本的代码更新这真的很重要，我今天弄了半天始终没能解决问题

**Comment by bubbliiiing** [comment]
我又要发问号了
？？
![image](https://user-images.githubusercontent.com/47347516/169677069-49828987-0a94-4d0a-b170-df2ac43e5b9c.png)

**Comment by wangbaoyi** [comment]
额  我的意思是keras的版本出的问题.....

**Comment by wangbaoyi** [comment]
难道我只要用tf2就能解决了？但是tf2那个不是没用到keras了嘛

**Comment by bubbliiiing** [comment]
我建议你下一个再说吧

**Comment by wangbaoyi** [comment]
我是keras的版本出问题的......  tf版本为2.4.0  keras为2.4.3

**Comment by wangbaoyi** [comment]
哈哈哈 好吧 那我去看看  可能是我刚接触keras这个 给混淆了吧////

**Comment by bubbliiiing** [comment]
对，你是混淆了

**Comment by wangbaoyi** [comment]
==我还是想搞清楚一个事情 keras就是tf？还是说他们都是单独的

**Comment by wangbaoyi** [comment]
既然是单独的那项目名称不应该取名为tf2yolo呀。，。。是我理解错误了嘛 难道up已经更新了呀  我先去下载看看吧 谢谢up解答

**Comment by bubbliiiing** [comment]
希望你调查清楚再问这个事情，这个问题太小白了。

**Comment by bubbliiiing** [comment]
https://blog.csdn.net/weixin_46824122/article/details/105421112

**Comment by bubbliiiing** [comment]
https://blog.csdn.net/weixin_46824122/article/details/105421112

**Comment by wangbaoyi** [comment]
嗯嗯  我的问题，。。。up可以给个好友位嘛 我就想单纯的赞助你

**Comment by wangbaoyi** [comment]
我就是那个B站说赞助你的那个人

**Comment by bubbliiiing** [comment]
你是私信发我的？我没看私信昨天…你先试试吧，可以用再说
